# yaml-language-server: $schema=./config-schema.json
# bucket:
#   connectionString: 's3://test'

host: 'localhost'

ingress:
  metadata:
    annotations:
      kubernetes.io/ingress.class: 'gce'
# redis:
#   user: ''
#   password: 'testing'
#   port: 6379
#   host: 'localhost'
#   params:
#     tls: 'true'
#   caCert: 'testomg'
